# -*- coding: utf-8 -*-
"""bgremove.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jq2-n_KN6ejlBOUsLwtq2lUYIyBYOrZQ
"""

im = Image.open("/content/man.jpg")
rgb_im = im.convert('RGB')
rgb_im.save('audacious.jpg')

# Importing Required Modules
from rembg import remove
from PIL import Image
  
# Store path of the image in the variable input_path
input_path =  '/content/im.jpg'
  
# Store path of the output image in the variable output_path
output_path = '/content/out.jpg'
  
# Processing the image
input = Image.open(input_path)
  
# Removing the background from the given Image
output = remove(input)
  
#Saving the image in the given path
output.save(output_path)

im = Image.open('/content/man.jpg').convert('RGB')

import matplotlib.pyplot as plt
plt.imshow(im)

pip install rembg

from rembg import remove
from PIL import Image

input_path = '/content/man.jpg' # input image path
output_path = '/content/output.png' # output image path

input = Image.open(input_path) # load image
output = remove(input) # remove background
output.save(output_path) # save image

